delete 0
thecoding2025/myproject pull request #1
Opened 2022-07-17 17:08 UTC by snows2001

숫자는 1부터지!

2022-07-17 17:26 UTC, thecoding2025 commented on number.txt
>  1
0부터지!

2022-07-17 17:28 UTC, thecoding2025 commented
불만이 많은듯.

2022-07-17 17:34 UTC, thecoding2025 commented on number.txt
>  2
이것도 다시

2022-07-17 17:34 UTC, thecoding2025 approved these changes
approve

2022-07-17 17:37 UTC, thecoding2025 requested changes

2022-07-17 17:37 UTC, thecoding2025 commented on number.txt
>  1
3을 추가해봐

2022-07-17 17:42 UTC, thecoding2025 reviewed
일반적인 코멘트

2022-07-17 17:42 UTC, thecoding2025 approved these changes
merge 승인

2022-07-17 17:44 UTC, thecoding2025 requested changes
Request changes

2022-07-17 17:51 UTC, thecoding2025 requested changes
해결해라!

2022-07-17 17:51 UTC, thecoding2025 commented on number.txt
> +0
0은 아니지!

2022-07-17 17:51 UTC, thecoding2025 commented on number.txt
>  1
이건 ok!

2022-07-17 17:51 UTC, thecoding2025 commented on number.txt
>  2
3을 더 추가해봐

2022-07-17 17:54 UTC, thecoding2025 commented on number.txt
> +0
sigle comment

2022-07-17 18:01 UTC, thecoding2025 commented on number.txt
> +0
리뷰

2022-07-17 18:04 UTC, snows2001 reviewed
해결완료

2022-07-17 18:06 UTC, thecoding2025 approved these changes

2022-07-19 15:55 UTC, snows2001 commented on number.txt
>  2
그건 b가 할일 아닌가?

2022-07-19 15:57 UTC, thecoding2025 commented on number.txt
>  2
하는 김에 해주삼

2022-07-19 16:07 UTC, thecoding2025 requested changes
일좀해줘

2022-07-19 16:07 UTC, thecoding2025 commented on number.txt
>  2
ㅐㅏ

2022-07-19 16:07 UTC, thecoding2025 commented on number.txt
>  2
3추가

2022-07-30 15:12 UTC, merged